dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'deb https://debian.neo4j.org/repo stable/'
        key_url: 'https://debian.neo4j.org/neotechnology.gpg.key'
    packages:
      - neo4j=1:3.5.*
sudo: true
language: python
python:
- '3.6'
services:
- neo4j
before_install:  # disable auth for neo4j and restart it...
- sudo sed -i 's/#dbms.security.auth_enabled=false/dbms.security.auth_enabled=false/g' /etc/neo4j/neo4j.conf
- sudo systemctl restart neo4j
install:
- pip install -e .
- pip install -r test-requirements.txt
script:
- make test
deploy:
  provider: pypi
  user: lyftpypi
  password: # see https://docs.travis-ci.com/user/encryption-keys/
    secure: QNMqTeJBIQ7TGhN1sLLy0N7s9EXaQVf3rkpACyKhDbmqiqtNHJ6KY9Wr+sRW8bE9hhEj4yC+ayZRRMfJyi74HtOUkwaChTgyOLHuWQQyJVHSPXSA5qWwZRt+ab1vwFL3is0SoNVjvA0VeQ2d6aPKhE8JRgTbTwL7sqrPZhft34cjoWfgk6VZ8R/NnPaMWnN7VdIkoFDfR0PXexpUXpoAjgQKelkZ9Q82PdgeWV259cmC75W9fIxsfwJoghPQhIIFgpypdoOSbSLblSqwsPS3hofAwdhnLjNcncswlKzipRdev/LDJLjxJkl2xNe77PvxlfYV3HdpcZerr8ZRLGrmgr6xKLkrVfzg6Z0vPVhUsnO0tzWq/bJxoXnH/Cz3500zq6eFzqEJrLXxcNTAM0CCbFmC8q8ykkT+e+tWJqutuPbmOtghYkWbv+K/Z0/0XSvY4iPJ3QvDlLh4jDdpU2tFFDESWa7NBjuM9ttho/q7yQP8yNwmlw8FdRXf4lsYSMm9VDppJDBdXN6ZNr2WMxlhqHREMO2rG8fcEbPs2wAzH46TTsN8LxFRCF0B58ciKLkN0ejPPvxJSzUR/qlbQfgP/XtL1mhLAsrbIW8zAgN2enE8VzTo35/t0q/D53W/PDUg0c8hh/3/ZmSJP29QLk7MQQcZaN2DQBkrx3dUeEq1YOA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: lyft/cartography
