openapi: 3.0.1
info:
  title: Cartography Fork
  description: <DESCRIPTION PLACEHOLDER>
  x-cortex-tag: security_cartography-fork
  x-cortex-service-groups:
    - library
  x-cortex-git:
    gitlab:
      repository: security/cartography-fork
  x-cortex-owners:
    - type: EMAIL
      email: taya.steere@grammarly.com
      description: Technical Owner
