version: "3.7"
services:
  neo4j:
    image: neo4j:4.4.35-community@sha256:548050168bc1c408bd6e5c6250ca2e1776db50555ab4a5f756ff0d94c98e1a8d
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./.compose/neo4j/conf:/conf
      - ./.compose/neo4j/data:/data
      - ./.compose/neo4j/import:/import
      - ./.compose/neo4j/logs:/logs
      - ./.compose/neo4j/plugins:/plugins
    environment:
      # Raise memory limits:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      # Auth:
      - NEO4J_AUTH=none
      # Add APOC and GDS:
      - apoc.export.file.enabled=true
      - apoc.import.file.enabled=true
      - apoc.import.file.use_neo4j_config=true
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_allowlist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
      # Networking:
      - dbms.connector.bolt.listen_address=0.0.0.0:7687
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:7474"]
        interval: 10s
        timeout: 10s
        retries: 10
  cartography:
    # As seen in docs, we build with `cd /path/to/cartography && docker build -t lyft/cartography .`
    # and then run with `docker-compose up -d`.
    image: lyft/cartography@sha256:13c8b17c9bba6339c57587e487bed17914dd57c321e605e051fc08c1d6e219ff
    # EXAMPLE: Our ENTRYPOINT is cartography, running specific command to sync AWS
    # command: ["-v", "--neo4j-uri=bolt://neo4j:7687", "--aws-sync-all-profiles"]
    user: cartography
    init: true
    restart: on-failure
    depends_on:
      - neo4j
    volumes:
      - ~/.aws:/cartography/.aws/
    environment:
      # Point to the neo4j service defined in this docker-compose file.
      - NEO4J_URL=bolt://cartography-neo4j-1:7687
