version: '3'
services:
  neo4j:
    environment:
      # The initial neo4j username MUST BE "neo4j" if a db user has not been previously created.
      # The initial neo4j password is tied to the docker volume
      # If you want to update the password you must update the account in neo4j
      # Then, you need to relaunch cartography process so it has the updated password
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    image: neo4j:3.5
    healthcheck:
      test: curl -i http://127.0.0.1:7474 2>&1 | grep -c -e '200 OK'
    ports:
      - "7687:7687" # host:container
      - "7474:7474"
    volumes:
      - $HOME/neo4j/data:/data

  cartography:
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - NEO4J_USERNAME
      - NEO4J_PASSWORD
    container_name: cartography
    image: cartography
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - neo4j
    command: "sh -c /home/app/run_cartography.sh"
