from pathlib import Path

import cartography.models.gsuite as gsuite_models
import cartography.models.keycloak as keycloak_models
import cartography.models.lastpass as lastpass_models
from cartography.models.introspection import DataModel
from cartography.models.introspection import inspect_data_model
from cartography.models.introspection import Node
from cartography.models.introspection import Relationship
from cartography.models.schema_docs import GENERATED_NOTICE
from cartography.models.schema_docs import render_module_schema
from cartography.models.schema_docs import write_module_schema_docs


def test_lastpass_schema_doc_is_generated_from_introspected_model():
    # Arrange
    model = inspect_data_model(lastpass_models)

    # Act
    generated = render_module_schema(model, "lastpass")

    # Assert
    assert not Path("docs/root/modules/lastpass/schema.md").exists()
    assert generated.startswith(GENERATED_NOTICE)
    assert "| **email** | Email address of the user. |" in generated
    assert "(:Human)-[:IDENTITY_LASTPASS]->(:LastpassUser)" in generated
    assert (
        "| **_ont_email** | Property generated by the ontology mapping. |" in generated
    )


def test_typed_analysis_jobs_are_rendered_from_introspected_model():
    # Arrange
    model = inspect_data_model(gsuite_models)

    # Act
    generated = render_module_schema(model, "gsuite")

    # Assert
    assert (
        "Analysis job `GSuite user map to Human` generates "
        "`(:Human)-[:IDENTITY_GSUITE]->(:GSuiteUser)`."
    ) in generated


def test_undirected_analysis_relationships_are_rendered_without_arrows():
    # Arrange
    node = Node(
        label="EC2KeyPair",
        descriptions=(),
        extra_labels=(),
        conditional_labels=(),
        properties=(),
        modules=("aws",),
        schemas=(),
    )
    relationship = Relationship(
        source_label="EC2KeyPair",
        label="MATCHING_FINGERPRINT",
        target_label="EC2KeyPair",
        direction=None,
        descriptions=(),
        properties=(),
        modules=("aws",),
        origins=("analysis",),
        schemas=(),
        analysis_jobs=(),
    )
    model = DataModel(nodes=(node,), relationships=(relationship,))

    # Act
    generated = render_module_schema(model, "aws")

    # Assert
    assert "EC2KeyPair ---|MATCHING_FINGERPRINT| EC2KeyPair" in generated
    assert "(:EC2KeyPair)-[:MATCHING_FINGERPRINT]-(:EC2KeyPair)" in generated


def test_keycloak_schema_doc_is_generated_from_introspected_model():
    # Arrange
    model = inspect_data_model(keycloak_models)

    # Act
    generated = render_module_schema(model, "keycloak")

    # Assert
    assert not Path("docs/root/modules/keycloak/schema.md").exists()
    assert len(model.relationships) == 36
    assert "Represents a Keycloak realm, which is a security domain" in generated
    assert "| **name** | The realm name (indexed for queries) |" in generated
    assert (
        "A user inherits membership in the parent groups of its direct groups."
        in generated
    )
    assert "(:KeycloakRole)-[:INDIRECT_GRANTS]->(:KeycloakScope)" in generated
    assert "(:KeycloakAuthenticationFlow)-[:NEXT_STEP]->" in generated
    assert "Deprecated compatibility edge linking a subgroup" in generated
    assert "Deprecated compatibility edge for a role assumed by a user." in generated


def test_write_module_schema_docs_preserves_manual_pages(
    tmp_path: Path,
):
    # Arrange
    model = inspect_data_model(lastpass_models)
    output_path = tmp_path / "lastpass" / "schema.md"
    output_path.parent.mkdir(parents=True)
    output_path.write_text("Manual schema\n")

    # Act
    write_module_schema_docs(
        model,
        ["lastpass"],
        output_root=tmp_path,
        preserve_existing=True,
    )

    # Assert
    assert output_path.read_text() == "Manual schema\n"


def test_write_module_schema_docs_creates_missing_pages(
    tmp_path: Path,
):
    # Arrange
    model = inspect_data_model(lastpass_models)
    output_path = tmp_path / "lastpass" / "schema.md"

    # Act
    write_module_schema_docs(
        model,
        ["lastpass"],
        output_root=tmp_path,
        preserve_existing=True,
    )

    # Assert
    assert output_path.read_text() == render_module_schema(model, "lastpass")
